# 绘图

## 1、绘制线段

In [9]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
print(img.shape)
#print(img)
cv.imshow('black', img)
cv.waitKey(0)
cv.destroyAllWindows()
# 绘制一条线宽为5的线段
# param1:背景图，param2:起点坐标，param3:终点坐标，param4:线颜色,param5:线粗细
cv.line(img, (0,0),(200,500),(0,0,255),1)

winname = 'example'
cv.namedWindow(winname)
cv.imshow(winname,img)
cv.waitKey(0)
cv.destroyAllWindows()

(512, 512, 3)


## 2、绘制矩形

In [5]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
# 画一个绿色边框的矩形，参数2：左上角坐标，参数3：右下角坐标
cv.rectangle(img, (100, 100), (402, 80), (0,255,255), 1)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 3、绘制圆

In [10]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
# 画一个填充红色的圆，参数2：圆心坐标，参数3：半径
cv.circle(img, (300,300), 63, (0,0,255), -1)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 4、绘制椭圆

In [15]:
import numpy as np
import cv2 as cv 
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
# 在图中心画一个填充的半圆
cv.ellipse(img, (256,256), (100,50), 0, 720, 180, (255,0,0), -1)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 5、绘制多边形

In [19]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3),np.uint8)
# 定义四个顶点坐标
pts = np.array([[100,100], [250,120], [120,200], [200,300]])
print(pts)
# 顶点个数：4，矩阵变成4*1*2维
pts = pts.reshape((-1, 1, 2))
print(pts)
#绘制椭圆
cv.polylines(img, [pts], False, (0, 255, 255))

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

[[100 100]
 [250 120]
 [120 200]
 [200 300]]
[[[100 100]]

 [[250 120]]

 [[120 200]]

 [[200 300]]]


## 6、添加文字

In [26]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
#添加文字
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img, 'hello',(50,200), font, 3,(0,255,255),5)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 7、综合图像绘制

In [28]:
import numpy as np
import cv2 as cv

# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)

# 绘制一条线宽为5的线段
cv.line(img, (0,0),(511,511),(255,0,0),1)

# 画一个绿色边框的矩形，参数2：左上角坐标，参数3：右下角坐标
cv.rectangle(img,(384,0),(510,128),(0,255,0),3)

# 画一个填充红色的圆，参数2：圆心坐标，参数3：半径
cv.circle(img, (447,63), 63, (0,0,255), -1)

# 在图中心画一个填充的半圆
cv.ellipse(img,(256,256), (100,50), 0, 0, 180, (255,0,0), -1)

#绘制多边形
pts = np.array([[10,5], [20,30], [70,20], [50,10]], np.int32)
pts = pts.reshape((-1,1,2))
cv.polylines(img,[pts], True, (0,0,255),1)
# 这里 reshape 的第一个参数为-1, 表明这一维的长度是根据后面的维度的计算出来的。
#添加文字
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img, 'Hello', (10,500), font, 4,(255,255,255),2)
cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 8、图像平移

In [31]:
import cv2 as cv
import numpy as np
im = cv.imread('images/img2.png')

# 构造移动矩阵H
# 在x轴方向移动多少距离，在y轴方向移动多少距离
H = np.float32([[1,0,50], [0,1,25]])
print(H)
rows, cols = img.shape[:2]
print(img.shape)
print(rows, cols)

# 注意这里rows和cols需要反置，即先列后行
res = cv.warpAffine(img, H, (2*cols, 2*rows))
cv.imshow('src', img)
cv.imshow('new', res)
cv.waitKey(0)
cv.destroyAllWindows()

[[ 1.  0. 50.]
 [ 0.  1. 25.]]
(512, 512, 3)
512 512


## 9、图像缩放

In [2]:
import cv2 as cv
import numpy as np

img = cv.imread('images/horses.jpg')
# 方法一：通过设置缩放比例，来对图像进行放大或缩小
res1 = cv.resize(img, None, fx=2, fy=2, interpolation=cv.INTER_CUBIC)

height, width = img.shape[:2]
# 方法二：直接设置图像的大小，不需要缩放因子
#cv2.INTER_NEAREST（最近邻插值） cv2.INTER_AREA （区域插值） cv2.INTER_CUBIC（三次样条插值） cv2.INTER_LANCZOS4（Lanczos插值）
res2 = cv.resize(img, (int(0.8*width), int(0.8*height)),interpolation=cv.INTER_LANCZOS4)

cv.imshow('src', img)
cv.imshow('res2', res2)

cv.waitKey(0)
cv.destroyAllWindows()

## 10、图像旋转

In [3]:
import cv2 as cv
import numpy as np

img = cv.imread('images/horses.jpg')
rows, cols = img.shape[:2]
#参数1：旋转中心，参数2：旋转角度，参数3：缩放因子
#参数3正为逆时针，负值为正时针
M = cv.getRotationMatrix2D((cols/2, rows/2), 45, 1)
print(M)
#第三个参数是输出图像的尺寸中心
dst = cv.warpAffine(img, M, (cols, rows))

while(1):
    cv.imshow('img',img)
    cv.imshow('img2',dst)
    #0xFF==27  ESC
    if cv.waitKey(1) & 0xFF==27:
        break
cv.destroyAllWindows()        

[[  0.70710678   0.70710678 -33.73863607]
 [ -0.70710678   0.70710678 170.54772721]]


## 11、仿射变换

In [2]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
#读取图片
src = cv.imread('images/horses.jpg')
#获取图像大小
rows, cols = src.shape[:2]
#设置图像仿射变换矩阵
pos1 = np.float32([[50,50], [200,50], [50,200]])
pos2 = np.float32([[10,100], [200,50], [100,250]])
M = cv.getAffineTransform(pos1, pos2)
print(M)
#图像仿射变换
result = cv.warpAffine(src, M, (2*cols, 2*rows))
#显示图像
cv.imshow('src', src)
cv.imshow('result', result)
#等待显示
cv.waitKey(0)
cv.destroyAllWindows()

[[  1.26666667   0.6        -83.33333333]
 [ -0.33333333   1.          66.66666667]]


## 12、透视变化

In [4]:
import cv2 as cv 
import numpy as np
import matplotlib.pyplot as plt
#读取图片
src = cv.imread('images/horses.jpg')
#获取图像大小
rows, cols = src.shape[:2]
#设置图像透视变换矩阵
pos1 = np.float32([[114,82],[287,156], [8,100],[143,177]])
pos2 = np.float32([[0,0],[188,0], [0,262],[188,262]])

M = cv.getPerspectiveTransform(pos1, pos2)
#图像透视变换
result = cv.warpPerspective(src, M, (2*cols, 2*rows))
#显示图像
cv.imshow('src', src)
cv.imshow('result', result)
#等待显示
cv.waitKey(0)
cv.destroyAllWindows()