# 绘图

## 1、绘制线段

In [9]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
print(img.shape)
#print(img)
cv.imshow('black', img)
cv.waitKey(0)
cv.destroyAllWindows()
# 绘制一条线宽为5的线段
# param1:背景图，param2:起点坐标，param3:终点坐标，param4:线颜色,param5:线粗细
cv.line(img, (0,0),(200,500),(0,0,255),1)

winname = 'example'
cv.namedWindow(winname)
cv.imshow(winname,img)
cv.waitKey(0)
cv.destroyAllWindows()

(512, 512, 3)


## 2、绘制矩形

In [5]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
# 画一个绿色边框的矩形，参数2：左上角坐标，参数3：右下角坐标
cv.rectangle(img, (100, 100), (402, 80), (0,255,255), 1)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 3、绘制圆

In [10]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
# 画一个填充红色的圆，参数2：圆心坐标，参数3：半径
cv.circle(img, (300,300), 63, (0,0,255), -1)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 4、绘制椭圆

In [15]:
import numpy as np
import cv2 as cv 
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
# 在图中心画一个填充的半圆
cv.ellipse(img, (256,256), (100,50), 0, 720, 180, (255,0,0), -1)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 5、绘制多边形

In [19]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3),np.uint8)
# 定义四个顶点坐标
pts = np.array([[100,100], [250,120], [120,200], [200,300]])
print(pts)
# 顶点个数：4，矩阵变成4*1*2维
pts = pts.reshape((-1, 1, 2))
print(pts)
#绘制椭圆
cv.polylines(img, [pts], False, (0, 255, 255))

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

[[100 100]
 [250 120]
 [120 200]
 [200 300]]
[[[100 100]]

 [[250 120]]

 [[120 200]]

 [[200 300]]]


## 6、添加文字

In [26]:
import numpy as np
import cv2 as cv
# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)
#添加文字
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img, 'hello',(50,200), font, 3,(0,255,255),5)

cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 7、综合图像绘制

In [28]:
import numpy as np
import cv2 as cv

# 创建一张黑色的背景图
img = np.zeros((512,512,3), np.uint8)

# 绘制一条线宽为5的线段
cv.line(img, (0,0),(511,511),(255,0,0),1)

# 画一个绿色边框的矩形，参数2：左上角坐标，参数3：右下角坐标
cv.rectangle(img,(384,0),(510,128),(0,255,0),3)

# 画一个填充红色的圆，参数2：圆心坐标，参数3：半径
cv.circle(img, (447,63), 63, (0,0,255), -1)

# 在图中心画一个填充的半圆
cv.ellipse(img,(256,256), (100,50), 0, 0, 180, (255,0,0), -1)

#绘制多边形
pts = np.array([[10,5], [20,30], [70,20], [50,10]], np.int32)
pts = pts.reshape((-1,1,2))
cv.polylines(img,[pts], True, (0,0,255),1)
# 这里 reshape 的第一个参数为-1, 表明这一维的长度是根据后面的维度的计算出来的。
#添加文字
font = cv.FONT_HERSHEY_SIMPLEX
cv.putText(img, 'Hello', (10,500), font, 4,(255,255,255),2)
cv.namedWindow('example')
cv.imshow('example', img)
cv.waitKey(0)
cv.destroyAllWindows()

## 8、图像平移

In [31]:
import cv2 as cv
import numpy as np
im = cv.imread('images/img2.png')

# 构造移动矩阵H
# 在x轴方向移动多少距离，在y轴方向移动多少距离
H = np.float32([[1,0,50], [0,1,25]])
print(H)
rows, cols = img.shape[:2]
print(img.shape)
print(rows, cols)

# 注意这里rows和cols需要反置，即先列后行
res = cv.warpAffine(img, H, (2*cols, 2*rows))
cv.imshow('src', img)
cv.imshow('new', res)
cv.waitKey(0)
cv.destroyAllWindows()

[[ 1.  0. 50.]
 [ 0.  1. 25.]]
(512, 512, 3)
512 512
